### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by nariox** [nariox/Linux-Simple-Fake-Background-Webcam#1]
- [x] Finish fixing Readme
- [x] Prettify prints
- [x] Fix inputs
- [x] Implement dynamic thresholding
- [ ] Allow threshold and other parameters to be set on-the-fly
- [ ] Improve how opening/closing operations work
- [x] Use temporal data to improve prediction
- [x] Implement adaptive background adjustment.
- [x] Currently, a big chunk of the CPU time is spent doing 2 Gaussian blur operations. I should consider using other/smaller blurs.
